'use client';

import { motion } from 'framer-motion';
import FadeIn from './FadeIn';

const features = [
  {
    emoji: '📱',
    title: 'Social Feed',
    description: 'Share workouts, progress photos, and achievements. React with custom emojis, comment with media, and follow friends on their fitness journey.',
    color: 'var(--teal)',
    bg: 'rgba(45,212,191,0.08)',
    border: 'rgba(45,212,191,0.2)',
  },
  {
    emoji: '💬',
    title: 'Real-time Chat',
    description: 'Group chats with @mentions, swipe-to-quote, media sharing, voice notes, and per-message emoji reactions. Stay connected between sessions.',
    color: '#A78BFA',
    bg: 'rgba(167,139,250,0.08)',
    border: 'rgba(167,139,250,0.2)',
  },
  {
    emoji: '🤖',
    title: 'AI Workout & Diet Plans',
    description: 'Get personalised workout and nutrition plans generated by AI based on your goals, fitness level, and schedule. Adapt and progress week by week.',
    color: 'var(--teal)',
    bg: 'rgba(45,212,191,0.08)',
    border: 'rgba(45,212,191,0.2)',
  },
  {
    emoji: '🥗',
    title: 'Nutrition Tracking',
    description: 'Log meals, track macros with visual rings, monitor water intake, and scan foods with AI lookup. Fuel your training with precision.',
    color: '#4ADE80',
    bg: 'rgba(74,222,128,0.08)',
    border: 'rgba(74,222,128,0.2)',
  },
  {
    emoji: '🏆',
    title: 'Achievements & Streaks',
    description: 'Earn badges for PRs, consistency, and milestones. Build streaks with grace days, celebrate with animated unlocks, and track your progress ring.',
    color: '#FBBF24',
    bg: 'rgba(251,191,36,0.08)',
    border: 'rgba(251,191,36,0.2)',
  },
  {
    emoji: '👥',
    title: 'Buddy System',
    description: 'Connect with gym buddies, follow their activity, celebrate their wins, and keep each other accountable with a dedicated social layer.',
    color: '#A78BFA',
    bg: 'rgba(167,139,250,0.08)',
    border: 'rgba(167,139,250,0.2)',
  },
  {
    emoji: '🏋️',
    title: 'Profile & Progress',
    description: 'A rich personal profile with your stats, personal records, workout history, achievements showcase, and a customisable public presence.',
    color: 'var(--teal)',
    bg: 'rgba(45,212,191,0.08)',
    border: 'rgba(45,212,191,0.2)',
  },
  {
    emoji: '⚔️',
    title: 'Challenges',
    description: 'Join community challenges and buddy challenges across different difficulty levels. Earn bonus points, track leaderboards, and push your limits.',
    color: '#F87171',
    bg: 'rgba(248,113,113,0.08)',
    border: 'rgba(248,113,113,0.2)',
  },
];

export default function Features() {
  return (
    <section id="features" className="section" style={{ position: 'relative' }}>
      <div className="orb orb-purple" style={{ width: '600px', height: '600px', top: '0', right: '-200px', opacity: 0.4 }} />

      <div className="container" style={{ position: 'relative', zIndex: 2 }}>
        <FadeIn>
          <div style={{ textAlign: 'center', marginBottom: '4rem' }}>
            <p className="section-label">Everything you need</p>
            <div className="divider" style={{ margin: '0.75rem auto 1rem' }} />
            <h2 style={{ fontFamily: 'var(--font-display)', fontSize: 'clamp(2rem, 4vw, 2.75rem)', fontWeight: 800, letterSpacing: '-0.02em', color: 'var(--text-primary)', marginBottom: '1rem' }}>
              Packed with features.{' '}
              <span className="gradient-text">Built for athletes.</span>
            </h2>
            <p style={{ color: 'var(--text-secondary)', maxWidth: '520px', margin: '0 auto', lineHeight: 1.7, fontSize: '0.975rem' }}>
              Everything you need to train smarter, stay accountable, and build a fitness community — all in one free app.
            </p>
          </div>
        </FadeIn>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(260px, 1fr))', gap: '1.25rem' }}>
          {features.map((feature, i) => (
            <FadeIn key={feature.title} delay={i * 60} direction="up">
              <motion.div
                className="glass"
                whileHover={{ y: -6, borderColor: feature.border }}
                style={{ borderRadius: '16px', padding: '1.75rem', height: '100%', cursor: 'default' }}
              >
                <div style={{ width: '48px', height: '48px', borderRadius: '12px', background: feature.bg, border: `1px solid ${feature.border}`, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '1.4rem', marginBottom: '1rem' }}>
                  {feature.emoji}
                </div>
                <h3 style={{ fontFamily: 'var(--font-display)', fontSize: '1rem', fontWeight: 700, color: feature.color, marginBottom: '0.6rem', letterSpacing: '-0.01em' }}>
                  {feature.title}
                </h3>
                <p style={{ color: 'var(--text-secondary)', fontSize: '0.875rem', lineHeight: 1.65 }}>
                  {feature.description}
                </p>
              </motion.div>
            </FadeIn>
          ))}
        </div>
      </div>
    </section>
  );
}
